version: '3'
services:
  app:
    build:
      # Either a path to a directory containing a Dockerfile, or a url to a git repository.
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/var/www/html
